// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS_t0qnA9cdP0AfCMmTNqRJ9sei4Hfhvk',
    appId: '1:63809265707:web:10d085e5ecfa6484f2ca6e',
    messagingSenderId: '63809265707',
    projectId: 'fir-91ae9',
    authDomain: 'fir-91ae9.firebaseapp.com',
    storageBucket: 'fir-91ae9.appspot.com',
    measurementId: 'G-1NGR80J7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzM3ajJslMFklj-UH0J6M68R9vsx5pjc',
    appId: '1:63809265707:android:ea7604eb1873d01ef2ca6e',
    messagingSenderId: '63809265707',
    projectId: 'fir-91ae9',
    storageBucket: 'fir-91ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAJMLWaCiUTd8y4w2H-0g_4Q09A4cXq4',
    appId: '1:63809265707:ios:9fa479258b212615f2ca6e',
    messagingSenderId: '63809265707',
    projectId: 'fir-91ae9',
    storageBucket: 'fir-91ae9.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVAJMLWaCiUTd8y4w2H-0g_4Q09A4cXq4',
    appId: '1:63809265707:ios:9fa479258b212615f2ca6e',
    messagingSenderId: '63809265707',
    projectId: 'fir-91ae9',
    storageBucket: 'fir-91ae9.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS_t0qnA9cdP0AfCMmTNqRJ9sei4Hfhvk',
    appId: '1:63809265707:web:c743be8a8343ed61f2ca6e',
    messagingSenderId: '63809265707',
    projectId: 'fir-91ae9',
    authDomain: 'fir-91ae9.firebaseapp.com',
    storageBucket: 'fir-91ae9.appspot.com',
    measurementId: 'G-K7BB0BPXGB',
  );
}
